# Generated by Django 4.0.4 on 2022-05-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_group_alter_student_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
        migrations.DeleteModel(
            name='StudentTeacher',
        ),
    ]
